config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: "registrations" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :instruments, only: [:index, :show] do
    resources :bookings, only: :create
  end

  resources :users, only: :show do
    resources :bookings, only: :index
  end

  resources :bookings, only: [:index, :update] do
    resources :reviews, only: [:create]
  end

  namespace :owner do
    resources :instruments, only: [:new, :create, :index, :edit, :update, :destroy]
    resources :bookings, only: [:index]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :instrument

  validates :instrument, presence: true
  validates :user, presence: true
  validates :date_start, presence: true
  validates :date_end, presence: true
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  CATEGORIES = ["Wind", "String", "Percussion", "Electronic"]

  geocoded_by :address
  after_validation :geocode
  belongs_to :user
  has_many :bookings
  has_attachment :photo

  validates :name, presence: true
  validates :category, inclusion: { in: CATEGORIES }
  validates :daily_price, presence: true
  validates :address, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :booking

  validates :comment, presence: true
  validates :title, presence: true
  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]
  has_many :instruments
  has_many :bookings

  has_many :instrument_bookings, through: :instruments, source: :bookings

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, uniqueness: true

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:first_name, :last_name, :phone_number])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :set_instrument, only: [:create]
  before_action :set_booking, only: [:update]

  def index
    @bookings = current_user.bookings
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.instrument = @instrument
    if @booking.save
      redirect_to bookings_path(@booking)
    else
      render 'instruments/show'
    end
  end

  def update
    # byebug
    @booking.update(booking_params)
    if @booking.save
      redirect_to bookings_path(@booking)
    else
      render 'bookings/index'
    end
  end

  private

  def set_instrument
    @instrument = Instrument.find(params[:instrument_id])
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:date_end, :date_start, :review, :rating)
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :set_instrument, only: :show

  def index
    @instruments = Instrument.all

    @instruments = Instrument.where.not(latitude: nil, longitude: nil)

    @hash = Gmaps4rails.build_markers(@instruments) do |instrument, marker|
      marker.lat instrument.latitude
      marker.lng instrument.longitude
      marker.infowindow render_to_string(partial: "/instruments/map_box", locals: { instrument: instrument })
    end
  end

  def show
    @booking = Booking.new
  end

  private

  def set_instrument
    @instrument = Instrument.find(params[:id])
  end
end

app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController

  def index
    @owner_bookings = current_user.instrument_bookings
  end
end

app/controllers/owner/instruments_controller.rb
class Owner::InstrumentsController < ApplicationController
  before_action :set_instrument, only: [:show, :edit, :update, :destroy]

  def index
    @instruments = current_user.instruments
  end

  def show
  end

  def new
    @instrument = Instrument.new
  end

  def create
    @instrument = Instrument.new(instrument_params)
    @instrument.user = current_user
    if @instrument.save
      redirect_to instrument_path(@instrument)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @instrument.update(instrument_params)
    if @instrument.save
      redirect_to instrument_path(@instrument)
    else
      render :edit
    end
  end

  def destroy
    @instrument.destroy
    redirect_to owner_instruments_path
  end

  private

  def set_instrument
    @instrument = Instrument.find(params[:id])
  end

  def instrument_params
    params.require(:instrument).permit(:name, :category, :description, :daily_price, :user_id, :address, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout :home

  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    instruments_path # Or :prefix_to_your_route
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @review.booking = @booking
    if @review.save
      redirect_to booking_path(@booking)
    else
      render 'bookings/index'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])
    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="form-booking">
  <p>Rent the instrument</p>
    <%= simple_form_for [@instrument, @booking] do |f| %>
      <div class="booking-form-inputs">
        <div class="input-start">
          <%= f.input :date_start, label: "From", as: :string, input_html: { data: { provide: 'datepicker' } } %>
        </div>
        <div class="input-end">
          <%= f.input :date_end, label: "To", as: :string, input_html: { data: { provide: 'datepicker' }  } %>
        </div>
      </div>
      <div class="center-btn">
        <%= f.submit 'Rent', class: 'btn btn-primary' %>
      </div>
    <% end %>
</div>

app/views/bookings/index.html.erb
<%= render 'navbar/profile_navbar' %>

<h1 class="text-center page-title">MY BOOKINGS</h1>

<% @bookings.each do |booking| %>
<div class="container-message">


  <div class="message">
    <% if booking.instrument.photo? %>
      <%= cl_image_tag booking.instrument.photo.path, width: '70', height: '70', crop: :fill %>
    <% else %>
      <%= image_tag("http://jakesmainstreetmusic.com/gfx/freeTextImage/placeholder.png", height: '70', width: '70', crop: :fill) %>
    <% end %>
    <div class="category-frame">
      <p><strong><%= booking.instrument.category %></strong></p>
      <p><%= @nbday = (booking.date_end - booking.date_start).to_i %> rent days</p>
    </div>
    <div class="message-body">
      <p><strong>Name : </strong><%= booking.instrument.name %></p>
      <p><strong>Owner : </strong><%= booking.user.first_name %> <%= booking.user.last_name %></p>
      <p><strong>Description : </strong><%= booking.instrument.description %></p>
      <p><strong>Duration : </strong>From <%= booking.date_start.strftime('%a %d %b %Y') %> to <%= booking.date_end.strftime('%a %d %b %Y') %>.</p>

      <div id="reviews">
        <% if booking.review.blank? %>
          Leave a review for this booking
        <% else %>
          <strong>Your review : </strong>
          <%= booking.review %>
          <p>
            <strong>Note : </strong>
            <%= "⭐️" * booking.rating %>
          </p>
        <% end %>
      </div>

    </div>
    <div class="message-status">
      <p class="status pending">Pending confirmation</p>
      <p> TOTAL PRICE </p>
      <p>
        <% @instrument = booking.instrument %>
        <%= (@nbday * @instrument.daily_price) %> €
      </p>
    </div>
</div>



    <div class="container-rating">

        <% if booking.review.blank? %>
        <p>
          <a class="btn btn-primary add-review" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            Add a review
          </a>
        </p>
        <div class="collapse" id="collapseExample">
          <div class="card card-body">
            <%= render 'reviews/form', booking: booking %>
          </div>
        </div>

        <% end %>
      </div>
    </div>

  </div>


  </div>
<% end %>

app/views/footer/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> at MusiLoc
  </div>
</div>

app/views/instruments/_map_box.html.erb
<%= instrument.inspect %>

app/views/instruments/index.html.erb
<div class="content">
  <div class="container">
    <div class="row">
      <% @instruments = Instrument.all %>
      <% @instruments.each do |instrument| %>
        <% if instrument.photo? %>
          <div class="col-xs-12 col-sm-6 col-md-4">
            <div class="card">
              <%= link_to instrument_path(instrument) do %>

                <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path instrument.photo.path, height: 300, width: 400, crop: :fill %>');">

                  <div class="card-category"><%= instrument.category %></div>
                  <div class="card-description">
                    <h2><%= instrument.name %></h2>
                    <p><%= instrument.daily_price %> €/hour</p>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        <% else %>
          <div class="col-xs-12 col-sm-6 col-md-4">
            <div class="card">
              <%= link_to instrument_path(instrument) do %>

                <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('http://www.fnacspectacles.com/static/0/visuel/300/365/SALLE-PLEYEL_3658025273903222756__1.jpg?1499677161000');">

                  <div class="card-category"><%= instrument.category %></div>
                  <div class="card-description">
                    <h2><%= instrument.name %></h2>
                    <p><%= instrument.daily_price %> €/hour</p>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div id="map" style="width: 100%; height: 600px;">
</div>



<% content_for(:after_js) do %>
  <%= javascript_tag do %>
  var styles = [
    {
        "stylers": [
            {
                "hue": "#007fff"
            },
            {
                "saturation": 89
            }
        ]
    },
    {
        "featureType": "water",
        "stylers": [
            {
                "color": "#ffffff"
            }
        ]
    },
    {
        "featureType": "administrative.country",
        "elementType": "labels",
        "stylers": [
            {
                "visibility": "off"
            }
        ]
    }
];
    var handler = Gmaps.build('Google');
    handler.buildMap({
      provider: { styles: styles  },
      internal: { id: 'map' } },
      function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(5);
        }
      }
    );
  <% end %>
  </div>
<% end %>

app/views/instruments/show.html.erb
<div class="container-instrument-show">
  <div class="btns-instrument btn-back">
    <%= link_to "Back to list", instruments_path, class: "btn btn-primary back-to-list" %>
  </div>
</div>

<h1 class="text-center page-title"><%= @instrument.name.upcase %></h1>
<div class="instrument-container">
  <div class="column-1">
    <div class="instrument-picture">
       <% if @instrument.photo? %>
        <%= cl_image_tag @instrument.photo.path, width: 200, height: 200, crop: :fill %>
      <% end %>
    </div>
    <br>
    <p class="category-style"><strong>Category :</strong> <%= @instrument.category %></p>
    <div class="btns-instrument">
      <% if current_user == @instrument.user %>
        <div class="btn-edit">
          <%= link_to "Edit", edit_owner_instrument_path(@instrument), class: "btn btn-primary" %>
        </div>
        <div class="btn-delete">
          <%= link_to "Delete", owner_instrument_path(@instrument), method: :delete, class: "btn btn-primary btn-update" %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="column-2">
    <p>
      <strong>Description :</strong>
      <br>
      <%= @instrument.description %>
    </p>
    <div class="instrument-price">
          <p><strong>Rent price : </strong><%= @instrument.daily_price %> €/day</p>
    </div>
    <% if current_user != @instrument.user %>
      <div class="instrument-booking">
        <div>
          <%= render 'bookings/form' %>
        </div>
      </div>
    <% end %>

  </div>

  <div class="column-3">
    <p><strong>Address : </strong><%= @instrument.address %></p>
    <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=10&size=400x300&sensor=false&maptype=roadmap&markers=color:blue|#{@instrument.address}&key=#{ENV["GOOGLE_API_SERVER_KEY"]}" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
      <%= content_for(:name) ? "Musiloc | #{yield(:name)} " : "Musiloc" %>
    </title>

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>

    <%= render (current_page?("/") ? "navbar/navbar-home" : "navbar/navbar") %>
    <%= render 'navbar/flashes' %>

    <%= yield %>

    <!-- <%= render 'footer/footer' %> -->

    <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=maps&key=#{ENV['GOOGLE_API_SERVER_KEY']}" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
    <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>


    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/navbar/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/navbar/_navbar-home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,40,168,0.6) 0%, rgba(0,30,61,0.6) 30%), url('https://wallpaperclicker.com/storage/wallpaper/cool-music-wallpaper-mobile-68707592.jpg');">
  <div class="banner-content">
    <div class="navbar-center">

  <!-- Navbar transparent -->
  <div class="navbar-home">

  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%#= link_to "Rent my instrument", new_owner_instrument_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to bookings_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Sign in"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link btn-white" %>
      <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path, class: "btn btn-primary" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to t(".sign_in", default: "Sign in"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
        </li>
        <li>
          <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
        </li>
        <li>
          <%= link_to "#" do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/navbar/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Rent my instrument", new_owner_instrument_path, class: "navbar-wagon-item navbar-wagon-link btn-rent-my-instrument" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to bookings_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to "Rent my instrument", new_owner_instrument_path, class: "navbar-wagon-item navbar-wagon-link btn-rent-my-instrument" %>
      <%= link_to t(".sign_in", default: "Sign in"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path, class: "btn btn-primary" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to t(".sign_in", default: "Sign in"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
        </li>
        <li>
          <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
        </li>
        <li>
          <%= link_to "#" do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/navbar/_profile_navbar.html.erb
<div class="profile_navbar">
  <div class="navbar-user">
      <%= link_to "All instruments", instruments_path, class: "navbar-wagon-item navbar-wagon-link user-link" %>
      <%= link_to "My bookings", bookings_path, class: "navbar-wagon-item navbar-wagon-link user-link" %>
      <%= link_to "My instruments", owner_instruments_path, class: "navbar-wagon-item navbar-wagon-link user-link" %>
      <%= link_to "My instruments bookings", owner_bookings_path, class: "navbar-wagon-item navbar-wagon-link user-link" %>
  </div>
</div>

app/views/owner/bookings/index.html.erb
<%= render 'navbar/profile_navbar' %>
<h1 class="text-center page-title">MY INSTRUMENTS BOOKINGS</h1>

<% @owner_bookings.each do |owner_b| %>
  <div class="message">
    <% if owner_b.instrument.photo? %>
      <%= cl_image_tag owner_b.instrument.photo.path, width: 70, height: 70, crop: :fill %>
    <% else %>
    <%= cl_image_tag("",
                 :width => 100, :height => 100,
                 :crop => :thumb, :gravity => :face, :radius => 20,
                 :default_image => "avatar.png") %>
    <% end %>

    <div class="category-frame text-center">
      <p><strong>RENT INFOS</strong></p>
      <p>
        <% @instrument = owner_b.instrument %>
        <% @nbday = (owner_b.date_end - owner_b.date_start).to_i %>
        <%= (@nbday * @instrument.daily_price) %> €
      </p>
      <p><%= @nbday %> rent days</p>
    </div>
    <div class="message-body">
      <p><strong><%= owner_b.instrument.name %></strong> - <%= owner_b.instrument.category %></p>
      <p><strong>Rent by : </strong><%= owner_b.user.first_name %> <%= owner_b.user.last_name %></p>
      <p>From <%= owner_b.date_start.strftime('%a %d %b %Y') %> to <%= owner_b.date_end.strftime('%a %d %b %Y') %>.</p>
    </div>
  </div>
<% end %>

app/views/owner/instruments/_form.html.erb
<div class="form-instrument">
  <%= simple_form_for [:owner, @instrument] do |f| %>
    <div class="form-inputs">
      <div class="col-md-4 col-md-offset-4">
        <%= f.input :name, placeholder: "e.g. : Guitare Fender Standard Strat", label: "Instrument name"%>
      </div>
      <div class="col-md-4 col-md-offset-4">
        <%= f.input :category, collection: ["Wind", "String", "Percussion", "Electronic"], prompt: "Select the right category" %>
      </div>
      <div class="col-md-4 col-md-offset-4">
        <%= f.input :description, placeholder: "Add your description", as: :text %>
      </div>
      <div class="col-md-4 col-md-offset-4">
         <%= f.input :daily_price, label: "Daily price (€)" %>
      </div>
      <div class="col-md-4 col-md-offset-4">
        <%= f.input :address %>
      </div>
      <div class="col-md-4 col-md-offset-4">
         <%= f.input :photo, label: "Instrument photo", as: :attachinary %>
      </div>
      <div class="col-md-4 col-md-offset-4 center-btn">
        <div class="form-actions">
          <%= f.submit 'Done', class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/owner/instruments/edit.html.erb
<div class="container">
  <h4 class="text-center">Change information of your instrument !</h4>
  <%= render 'form' %>
</div>

app/views/owner/instruments/index.html.erb
<%= render 'navbar/profile_navbar' %>
<h1 class="text-center page-title">MY INSTRUMENTS</h1>

  <% @instruments.each do |instrument| %>
  <div class="instruments-list">
    <% if instrument.photo? %>
      <%= cl_image_tag instrument.photo.path, width: 70, height: 70, crop: :fill %>
    <% else %>
    <%= cl_image_tag("",
                 :width => 100, :height => 100,
                 :crop => :thumb, :gravity => :face, :radius => 20,
                 :default_image => "avatar.png") %>
    <% end %>
    <div class="instrument-category">
      <p><strong>Name : </strong><%= instrument.name %></p>
      <p><strong>Category : </strong><%= instrument.category %></p>
    </div>
    <div class="instrument-list-body">
      <p><strong>Description : </strong><%= instrument.description %></p>
      <p><strong>Price : </strong><%= instrument.daily_price %> €/day</p>
      <p><strong>Address : </strong><%= instrument.address %></p>
    </div>
    <div class="btn-view">
      <%= link_to "View", instrument_path(instrument), class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/owner/instruments/new.html.erb
<div class="container">
  <h4 class="text-center page-title">Add your instrument to rent !</h4>
  <%= render 'form' %>
</div>

app/views/pages/home.html.erb
<div class="banner-content">
  <p>
    Rent your instrument
  </p>
  <%= link_to "Find an instrument", instruments_path, class: "btn btn-primary btn-lg btn-home"%>
  <%= link_to "Rent my instrument", new_owner_instrument_path, class: "btn btn-primary btn-lg btn-home"%>
  </div>
</div>


  <div class="typewriter">
    <h1>Musiloc</h1>
  </div>

app/views/reviews/_form.html.erb
<%= simple_form_for booking do |f| %>
<%= f.input :rating %>
<%= f.input :review %>
  <div class="btn-post">
    <%= f.submit 'Post', class: 'btn btn-primary btn-post' %>
  </div>
<% end %>

app/views/reviews/_show.html.erb
<p><%= review.content %></p>

app/views/users/show.html.erb
<%= @user.last_name %>
<%= @user.first_name %>